### ISSUE TITLE
Organización

### ISSUE THREAD

**Issue by francoa** [francoa/Tesis#1]
Deberíamos organizarnos para no andar pisando lo que escribe el otro.

Está claro que el capítulo 4 es tuyo y el 5 mío, pero deberíamos ver qué onda con el resto.

Por ejemplo, ahora estoy tocando la intro del capítulo 3 (apenas), pero me fije que en tu último commit en el capítulo 3 habías cambiado la intro.

Voy a modificar poco la intro, pero tengo que hacerlo porque pienso agregar una sección (en aras de hacer el "cuentito" de claudio), igual estaría bueno que no nos pisemos para el resto.

**Comment by francoa** [comment]
la asignación es sólo para que te llegue al mail jajaj

**Comment by andresmanelli** [comment]
Juntemonos un dia a verlo. Llegan al mail igual los issues jaj.

**Comment by francoa** [comment]
en realidad te lo asigné porque lo tenés que hacer vos, ya está decidido.

Atentamente, te cagué

:P
