### ISSUE TITLE
Capítulo 3 necesita trabajo

### ISSUE THREAD

**Issue by francoa** [francoa/Tesis#3]
A saber:
- [x] Explicar mejor la sección de resultados (en el sentido de hacer "el cuentito").
- [x] Completar Tabla 3.1 con los datos de todas las temperaturas.
- [x] Rehacer Tablas 3.2 y 3.3 con fits tomando las temperaturas faltantes.
- [x] Rehacer Figuras 3.3 a 3.5 con los datos de todas las temperaturas.
- [x] Rehacer Figura 3.6 con los datos de todas las temperaturas e incluir la curva de Johnson que parece se borró.
- [x] Graficar muestra con condición de frontera libre para deformación atómica y ver si aparecen shear bands. Nunca hicimos esto. Figuras 3.10 y 3.11.
- [x] Cambiar todo lo que diga que no hay shearbands.

**Comment by andresmanelli** [comment]
Hora de cerrar issues?
